spring:
  datasource:
    password:
    username: sa
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    hikari:
      connection-test-query: values 1
  h2:
    console:
      enabled: true
      path: /h2

  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create